version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - nodejs2023Q2-data:/var/lib/postgresql/data
    ports:
        - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nodejs2023Q2-student -d nodejs2023Q2-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
#      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
#      PGADMIN_CONFIG_SERVER_MODE: "${PGADMIN_CONFIG_SERVER_MODE}"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    ports:
#      - "${PGADMIN_PORT}:${PGADMIN_PORT_OUT}"
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#    networks:
#      - postgres
#
#  home-library:
#    container_name: home-library_container
#    image: kirilldemyanenko/home-library
#    environment:
#        DB_HOST: postgres
#        DB_PORT: "${DB_PORT}"
#        DB_USERNAME: "${DB_USERNAME}"
#        DB_PASSWORD: "${DB_PASSWORD}"
#        DB_NAME: "${DB_NAME}"
#    volumes:
#      - home-library-data:/var/lib/home-library
#    ports:
#      - "${APP_PORT}:${APP_PORT}"
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#    networks:
#      - postgres
#
volumes:
  nodejs2023Q2-data:
  pgadmin-data:
  home-library-data:

networks:
  postgres:
    driver: bridge
